### ISSUE TITLE
bug:(engine): fail on autostart STREAM or SERVICE

### ISSUE THREAD

**Issue by pcanto-hopeit** [hopeit-git/hopeit.engine#121]
When you start hopeit.engine app with --start-streams argument, the engine don't start streams or services.
Anyway you can start any stream or service from the management api:
`curl localhost:8020/mgmt/simple-example/0x14/streams/process-events/start`

it looks related to _start_streams method in the create_task

**Comment by leosmerling-hopeit** [comment]
Fixed in #125 (Release 0.14.1)
