### ISSUE TITLE
feature(engine): startup only selected groups of events

### ISSUE THREAD

**Issue by leosmerling-hopeit** [hopeit-git/hopeit.engine#130]
## Motivation
Now when starting a hopeit app, using `hopeit_server` cli, it will start all events including endpoints and streams (with `--start-streams` specified).

Sometimes it is needed to start different events (especially for stream processing) in separated deployments/runtimes. 

## Solution
Enable `hopeit_server` cli to start a defined list of events, based on a `groups` label specified in the application config file.
```
"events": {
  "event1": {
    "type": "GET",
    "group": "group1"
  },
  "event2": {
    "type": "STREAM",
    "group": "group1"
  },
  "event3": {
    "type": "STREAM",
    "group": "group2"
  },
  "event4": {
    "type": "POST",
    "group": "group2"
  },
 "healthcheck": {
   "type": "GET
 }
}
```

Then:
`hopeit_server --groups=group1 ...` will starts `event1`, `event2` and  `healthcheck`  in the current instance, when an event like `healthcheck` has no groups specified it will by asumed  as `group: 'DEFAULT'` Note: events from group `DEFAULT` allway start.
`hopeit_server --groups=group2 ...` will start `event3` ,`event4` and  `healthcheck`
`hopeit_server --groups=group2,DEFAULT` will start `event3`, `event4` and `healthcheck` events, same as before line.
`hopeit_server --groups=DEFAULT` will start only `healthcheck`, when an event like `healthcheck` has no groups specified it will by asumed  as `group: 'DEFAULT'`
`hopeit_server ....` without group parameters, will start all events.

#### Default behavior / backward compatibility
When `hopeit_server` is started with no `--groups` parameters, ALL events will be started.
When no group is specified for an event, it will be assumed as `DEFAULT` group, i.e.: `group: 'DEFAULT'`

**Comment by pcanto-hopeit** [comment]
hello @leosmerling-hopeit, I updated the spec of this issue and uploaded a #131 to implement the feature

**Comment by leosmerling-hopeit** [comment]
@pcanto-hopeit I've reviewed and requested changes on #131. Mostly due to the following, that will require re-adapting this spec:

> I strongly suggest that we limit the number of groups for an event to a single one, instead of a list in order to avoid multiple ways to achieve the same effect by different configuration criteria. In case an event needs to be enabled in multiple deployments, it needs to be put in a group that is enabled in the comma-separated list in hopeit_server command line.
