### ISSUE TITLE
deprecation(engine): event_api method remove `title` parameter, use `summary` instead

### ISSUE THREAD

**Issue by pcanto-hopeit** [hopeit-git/hopeit.engine#26]
Starting hopeit.engine 0.2.0 version `title` parameter will be remove from event_api method, use summary instead.

- [x] make `event_api` named parameter method and remove `title` parameter.
- [ ] bump version.
- [ ] add removal note to release notes.

Related #25

**Comment by leosmerling-hopeit** [comment]
@pcanto-hopeit 

please prepare a PR to implement this deprecation.
